/**
 * Static demo data for the HNL draft prototype.
 *
 * Club-season membership is intended to be plausible and auditable against the
 * research report. Every OVR, component score, scoring weight, and opponent
 * strength is editorial demo data—not an HNS, club, Transfermarkt, or
 * Soccerway rating.
 */

export type Position = "GK" | "DEF" | "MID" | "FWD";

export type PlayerRole =
  | "GK"
  | "RB"
  | "CB"
  | "LB"
  | "WB"
  | "DM"
  | "CM"
  | "AM"
  | "RW"
  | "LW"
  | "ST";

export type FormationSlot = {
  id: string;
  label: string;
  position: Position;
  acceptedRoles: readonly PlayerRole[];
};

export type Formation = {
  id: "4-3-3" | "4-2-3-1" | "3-5-2" | "4-4-2-diamond";
  name: string;
  description: string;
  slots: readonly FormationSlot[];
};

export type DraftPlayer = {
  id: string;
  name: string;
  club: string;
  season: string;
  position: Position;
  role: PlayerRole;
  ovr: number;
  attack: number;
  midfield: number;
  defence: number;
  goalkeeper: number;
  scoringWeight: number;
  accent: string;
  eligibleRoles: readonly PlayerRole[];
  ratingKind: "editorial-demo";
};

export type ClubOpponent = {
  id: string;
  name: string;
  shortName: string;
  city: string;
  season: "2026/27";
  attack: number;
  midfield: number;
  defence: number;
  goalkeeper: number;
  bench: number;
  accent: string;
  ratingKind: "editorial-demo";
};

export const editorialDisclosure =
  "Demo only: every OVR, ATT/MID/DEF/GK component, scoring weight, and opponent strength is an editorial prototype input. HNS supplies competition rules and results, not these ratings. Do not present them as official, predictive, or betting data.";

export const formations: readonly Formation[] = [
  {
    id: "4-3-3",
    name: "4-3-3",
    description: "Balanced default with a holding midfielder and two wide forwards.",
    slots: [
      { id: "gk", label: "GK", position: "GK", acceptedRoles: ["GK"] },
      { id: "rb", label: "RB", position: "DEF", acceptedRoles: ["RB", "WB", "CB"] },
      { id: "rcb", label: "RCB", position: "DEF", acceptedRoles: ["CB"] },
      { id: "lcb", label: "LCB", position: "DEF", acceptedRoles: ["CB"] },
      { id: "lb", label: "LB", position: "DEF", acceptedRoles: ["LB", "WB", "CB"] },
      { id: "dm", label: "DM", position: "MID", acceptedRoles: ["DM", "CM"] },
      { id: "cm", label: "CM", position: "MID", acceptedRoles: ["CM", "DM", "AM"] },
      { id: "am", label: "AM", position: "MID", acceptedRoles: ["AM", "CM"] },
      { id: "rw", label: "RW", position: "FWD", acceptedRoles: ["RW", "LW", "AM"] },
      { id: "st", label: "ST", position: "FWD", acceptedRoles: ["ST"] },
      { id: "lw", label: "LW", position: "FWD", acceptedRoles: ["LW", "RW", "AM"] },
    ],
  },
  {
    id: "4-2-3-1",
    name: "4-2-3-1",
    description: "Two deeper midfielders behind a mobile attacking line.",
    slots: [
      { id: "gk", label: "GK", position: "GK", acceptedRoles: ["GK"] },
      { id: "rb", label: "RB", position: "DEF", acceptedRoles: ["RB", "WB", "CB"] },
      { id: "rcb", label: "RCB", position: "DEF", acceptedRoles: ["CB"] },
      { id: "lcb", label: "LCB", position: "DEF", acceptedRoles: ["CB"] },
      { id: "lb", label: "LB", position: "DEF", acceptedRoles: ["LB", "WB", "CB"] },
      { id: "rdm", label: "RDM", position: "MID", acceptedRoles: ["DM", "CM"] },
      { id: "ldm", label: "LDM", position: "MID", acceptedRoles: ["DM", "CM"] },
      { id: "rw", label: "RW", position: "FWD", acceptedRoles: ["RW", "LW", "AM"] },
      { id: "am", label: "AM", position: "MID", acceptedRoles: ["AM", "CM"] },
      { id: "lw", label: "LW", position: "FWD", acceptedRoles: ["LW", "RW", "AM"] },
      { id: "st", label: "ST", position: "FWD", acceptedRoles: ["ST"] },
    ],
  },
  {
    id: "3-5-2",
    name: "3-5-2",
    description: "Three centre-backs, energetic wing-backs, and a strike pair.",
    slots: [
      { id: "gk", label: "GK", position: "GK", acceptedRoles: ["GK"] },
      { id: "rcb", label: "RCB", position: "DEF", acceptedRoles: ["CB", "RB"] },
      { id: "cb", label: "CB", position: "DEF", acceptedRoles: ["CB"] },
      { id: "lcb", label: "LCB", position: "DEF", acceptedRoles: ["CB", "LB"] },
      { id: "rwb", label: "RWB", position: "DEF", acceptedRoles: ["WB", "RB", "RW"] },
      { id: "dm", label: "DM", position: "MID", acceptedRoles: ["DM", "CM"] },
      { id: "cm", label: "CM", position: "MID", acceptedRoles: ["CM", "DM", "AM"] },
      { id: "am", label: "AM", position: "MID", acceptedRoles: ["AM", "CM"] },
      { id: "lwb", label: "LWB", position: "DEF", acceptedRoles: ["WB", "LB", "LW"] },
      { id: "rst", label: "RST", position: "FWD", acceptedRoles: ["ST", "RW"] },
      { id: "lst", label: "LST", position: "FWD", acceptedRoles: ["ST", "LW"] },
    ],
  },
  {
    id: "4-4-2-diamond",
    name: "4-4-2 Diamond",
    description: "A narrow midfield diamond with two complementary forwards.",
    slots: [
      { id: "gk", label: "GK", position: "GK", acceptedRoles: ["GK"] },
      { id: "rb", label: "RB", position: "DEF", acceptedRoles: ["RB", "WB", "CB"] },
      { id: "rcb", label: "RCB", position: "DEF", acceptedRoles: ["CB"] },
      { id: "lcb", label: "LCB", position: "DEF", acceptedRoles: ["CB"] },
      { id: "lb", label: "LB", position: "DEF", acceptedRoles: ["LB", "WB", "CB"] },
      { id: "dm", label: "DM", position: "MID", acceptedRoles: ["DM", "CM"] },
      { id: "rcm", label: "RCM", position: "MID", acceptedRoles: ["CM", "DM", "AM"] },
      { id: "lcm", label: "LCM", position: "MID", acceptedRoles: ["CM", "DM", "AM"] },
      { id: "am", label: "AM", position: "MID", acceptedRoles: ["AM", "CM"] },
      { id: "rst", label: "RST", position: "FWD", acceptedRoles: ["ST", "RW"] },
      { id: "lst", label: "LST", position: "FWD", acceptedRoles: ["ST", "LW"] },
    ],
  },
] as const;

export const hnlClubs: readonly ClubOpponent[] = [
  {
    id: "gnk-dinamo",
    name: "GNK Dinamo",
    shortName: "Dinamo",
    city: "Zagreb",
    season: "2026/27",
    attack: 84,
    midfield: 84,
    defence: 82.5,
    goalkeeper: 82,
    bench: 76,
    accent: "#0057B8",
    ratingKind: "editorial-demo",
  },
  {
    id: "hnk-hajduk",
    name: "HNK Hajduk",
    shortName: "Hajduk",
    city: "Split",
    season: "2026/27",
    attack: 80.5,
    midfield: 79,
    defence: 78,
    goalkeeper: 79.5,
    bench: 73,
    accent: "#E32636",
    ratingKind: "editorial-demo",
  },
  {
    id: "hnk-rijeka",
    name: "HNK Rijeka",
    shortName: "Rijeka",
    city: "Rijeka",
    season: "2026/27",
    attack: 79,
    midfield: 78.5,
    defence: 79,
    goalkeeper: 78,
    bench: 72.5,
    accent: "#6CBFEF",
    ratingKind: "editorial-demo",
  },
  {
    id: "nk-varazdin",
    name: "NK Varaždin",
    shortName: "Varaždin",
    city: "Varaždin",
    season: "2026/27",
    attack: 75,
    midfield: 74.5,
    defence: 76,
    goalkeeper: 74,
    bench: 69.5,
    accent: "#004A8F",
    ratingKind: "editorial-demo",
  },
  {
    id: "nk-istra-1961",
    name: "NK Istra 1961",
    shortName: "Istra 1961",
    city: "Pula",
    season: "2026/27",
    attack: 74,
    midfield: 75,
    defence: 75.5,
    goalkeeper: 74,
    bench: 69.5,
    accent: "#E7C51D",
    ratingKind: "editorial-demo",
  },
  {
    id: "nk-slaven-belupo",
    name: "NK Slaven Belupo",
    shortName: "Slaven",
    city: "Koprivnica",
    season: "2026/27",
    attack: 73.5,
    midfield: 73,
    defence: 72.5,
    goalkeeper: 72,
    bench: 68.5,
    accent: "#D51F2B",
    ratingKind: "editorial-demo",
  },
  {
    id: "nk-osijek",
    name: "NK Osijek",
    shortName: "Osijek",
    city: "Osijek",
    season: "2026/27",
    attack: 72.5,
    midfield: 74,
    defence: 73,
    goalkeeper: 74,
    bench: 69,
    accent: "#174EA6",
    ratingKind: "editorial-demo",
  },
  {
    id: "nk-lokomotiva",
    name: "NK Lokomotiva",
    shortName: "Lokomotiva",
    city: "Zagreb",
    season: "2026/27",
    attack: 73.5,
    midfield: 74,
    defence: 71.5,
    goalkeeper: 71,
    bench: 68,
    accent: "#315D9B",
    ratingKind: "editorial-demo",
  },
  {
    id: "hnk-gorica",
    name: "HNK Gorica",
    shortName: "Gorica",
    city: "Velika Gorica",
    season: "2026/27",
    attack: 72,
    midfield: 72.5,
    defence: 71.5,
    goalkeeper: 72,
    bench: 67.5,
    accent: "#D7192D",
    ratingKind: "editorial-demo",
  },
  {
    id: "nk-rudes",
    name: "NK Rudeš",
    shortName: "Rudeš",
    city: "Zagreb",
    season: "2026/27",
    attack: 68,
    midfield: 68.5,
    defence: 67.5,
    goalkeeper: 67,
    bench: 64,
    accent: "#D2A51D",
    ratingKind: "editorial-demo",
  },
] as const;

export const draftPlayers: readonly DraftPlayer[] = [
  // Goalkeepers
  {
    id: "livakovic-dinamo-2020-21",
    name: "Dominik Livaković",
    club: "GNK Dinamo",
    season: "2020/21",
    position: "GK",
    role: "GK",
    ovr: 87,
    attack: 15,
    midfield: 42,
    defence: 82,
    goalkeeper: 90,
    scoringWeight: 0.001,
    accent: "#0057B8",
    eligibleRoles: ["GK"],
    ratingKind: "editorial-demo",
  },
  {
    id: "pletikosa-hajduk-2001-02",
    name: "Stipe Pletikosa",
    club: "HNK Hajduk",
    season: "2001/02",
    position: "GK",
    role: "GK",
    ovr: 86,
    attack: 14,
    midfield: 38,
    defence: 81,
    goalkeeper: 89,
    scoringWeight: 0.001,
    accent: "#E32636",
    eligibleRoles: ["GK"],
    ratingKind: "editorial-demo",
  },
  {
    id: "subasic-hajduk-2010-11",
    name: "Danijel Subašić",
    club: "HNK Hajduk",
    season: "2010/11",
    position: "GK",
    role: "GK",
    ovr: 85,
    attack: 16,
    midfield: 43,
    defence: 80,
    goalkeeper: 87,
    scoringWeight: 0.001,
    accent: "#E32636",
    eligibleRoles: ["GK"],
    ratingKind: "editorial-demo",
  },
  {
    id: "ladic-croatia-zagreb-1997-98",
    name: "Dražen Ladić",
    club: "Croatia Zagreb",
    season: "1997/98",
    position: "GK",
    role: "GK",
    ovr: 88,
    attack: 12,
    midfield: 37,
    defence: 83,
    goalkeeper: 91,
    scoringWeight: 0.001,
    accent: "#0057B8",
    eligibleRoles: ["GK"],
    ratingKind: "editorial-demo",
  },
  {
    id: "vargic-rijeka-2015-16",
    name: "Ivan Vargić",
    club: "HNK Rijeka",
    season: "2015/16",
    position: "GK",
    role: "GK",
    ovr: 83,
    attack: 13,
    midfield: 39,
    defence: 78,
    goalkeeper: 85,
    scoringWeight: 0.001,
    accent: "#6CBFEF",
    eligibleRoles: ["GK"],
    ratingKind: "editorial-demo",
  },
  {
    id: "labrovic-rijeka-2023-24",
    name: "Nediljko Labrović",
    club: "HNK Rijeka",
    season: "2023/24",
    position: "GK",
    role: "GK",
    ovr: 82,
    attack: 13,
    midfield: 40,
    defence: 78,
    goalkeeper: 84,
    scoringWeight: 0.001,
    accent: "#6CBFEF",
    eligibleRoles: ["GK"],
    ratingKind: "editorial-demo",
  },

  // Defenders
  {
    id: "srna-hajduk-2002-03",
    name: "Darijo Srna",
    club: "HNK Hajduk",
    season: "2002/03",
    position: "DEF",
    role: "RB",
    ovr: 88,
    attack: 81,
    midfield: 87,
    defence: 85,
    goalkeeper: 8,
    scoringWeight: 0.7,
    accent: "#E32636",
    eligibleRoles: ["RB", "WB", "CM"],
    ratingKind: "editorial-demo",
  },
  {
    id: "simunic-dinamo-2012-13",
    name: "Josip Šimunić",
    club: "GNK Dinamo",
    season: "2012/13",
    position: "DEF",
    role: "CB",
    ovr: 87,
    attack: 51,
    midfield: 69,
    defence: 92,
    goalkeeper: 8,
    scoringWeight: 0.35,
    accent: "#0057B8",
    eligibleRoles: ["CB"],
    ratingKind: "editorial-demo",
  },
  {
    id: "gvardiol-dinamo-2020-21",
    name: "Joško Gvardiol",
    club: "GNK Dinamo",
    season: "2020/21",
    position: "DEF",
    role: "CB",
    ovr: 88,
    attack: 68,
    midfield: 81,
    defence: 91,
    goalkeeper: 8,
    scoringWeight: 0.35,
    accent: "#0057B8",
    eligibleRoles: ["CB", "LB"],
    ratingKind: "editorial-demo",
  },
  {
    id: "pranjic-osijek-2003-04",
    name: "Danijel Pranjić",
    club: "NK Osijek",
    season: "2003/04",
    position: "DEF",
    role: "LB",
    ovr: 84,
    attack: 77,
    midfield: 84,
    defence: 79,
    goalkeeper: 7,
    scoringWeight: 0.55,
    accent: "#174EA6",
    eligibleRoles: ["LB", "WB", "CM", "LW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "corluka-dinamo-2006-07",
    name: "Vedran Ćorluka",
    club: "GNK Dinamo",
    season: "2006/07",
    position: "DEF",
    role: "RB",
    ovr: 86,
    attack: 64,
    midfield: 76,
    defence: 89,
    goalkeeper: 8,
    scoringWeight: 0.3,
    accent: "#0057B8",
    eligibleRoles: ["RB", "CB"],
    ratingKind: "editorial-demo",
  },
  {
    id: "lovren-dinamo-2009-10",
    name: "Dejan Lovren",
    club: "GNK Dinamo",
    season: "2009/10",
    position: "DEF",
    role: "CB",
    ovr: 84,
    attack: 54,
    midfield: 68,
    defence: 88,
    goalkeeper: 8,
    scoringWeight: 0.3,
    accent: "#0057B8",
    eligibleRoles: ["CB"],
    ratingKind: "editorial-demo",
  },
  {
    id: "simic-croatia-zagreb-1997-98",
    name: "Dario Šimić",
    club: "Croatia Zagreb",
    season: "1997/98",
    position: "DEF",
    role: "CB",
    ovr: 87,
    attack: 55,
    midfield: 72,
    defence: 91,
    goalkeeper: 8,
    scoringWeight: 0.28,
    accent: "#0057B8",
    eligibleRoles: ["CB", "RB"],
    ratingKind: "editorial-demo",
  },
  {
    id: "vrsaljko-dinamo-2011-12",
    name: "Šime Vrsaljko",
    club: "GNK Dinamo",
    season: "2011/12",
    position: "DEF",
    role: "RB",
    ovr: 84,
    attack: 75,
    midfield: 80,
    defence: 82,
    goalkeeper: 7,
    scoringWeight: 0.42,
    accent: "#0057B8",
    eligibleRoles: ["RB", "WB", "LB"],
    ratingKind: "editorial-demo",
  },
  {
    id: "sosa-dinamo-2017-18",
    name: "Borna Sosa",
    club: "GNK Dinamo",
    season: "2017/18",
    position: "DEF",
    role: "LB",
    ovr: 82,
    attack: 74,
    midfield: 79,
    defence: 80,
    goalkeeper: 7,
    scoringWeight: 0.4,
    accent: "#0057B8",
    eligibleRoles: ["LB", "WB"],
    ratingKind: "editorial-demo",
  },
  {
    id: "drpic-dinamo-2007-08",
    name: "Dino Drpić",
    club: "GNK Dinamo",
    season: "2007/08",
    position: "DEF",
    role: "CB",
    ovr: 81,
    attack: 50,
    midfield: 64,
    defence: 85,
    goalkeeper: 8,
    scoringWeight: 0.25,
    accent: "#0057B8",
    eligibleRoles: ["CB"],
    ratingKind: "editorial-demo",
  },

  // Midfielders
  {
    id: "brozovic-dinamo-2013-14",
    name: "Marcelo Brozović",
    club: "GNK Dinamo",
    season: "2013/14",
    position: "MID",
    role: "DM",
    ovr: 87,
    attack: 76,
    midfield: 91,
    defence: 84,
    goalkeeper: 7,
    scoringWeight: 0.75,
    accent: "#0057B8",
    eligibleRoles: ["DM", "CM"],
    ratingKind: "editorial-demo",
  },
  {
    id: "modric-dinamo-2007-08",
    name: "Luka Modrić",
    club: "GNK Dinamo",
    season: "2007/08",
    position: "MID",
    role: "CM",
    ovr: 91,
    attack: 86,
    midfield: 95,
    defence: 78,
    goalkeeper: 7,
    scoringWeight: 1.0,
    accent: "#0057B8",
    eligibleRoles: ["CM", "AM", "DM"],
    ratingKind: "editorial-demo",
  },
  {
    id: "olmo-dinamo-2018-19",
    name: "Dani Olmo",
    club: "GNK Dinamo",
    season: "2018/19",
    position: "MID",
    role: "AM",
    ovr: 89,
    attack: 90,
    midfield: 92,
    defence: 55,
    goalkeeper: 6,
    scoringWeight: 1.15,
    accent: "#0057B8",
    eligibleRoles: ["AM", "CM", "RW", "LW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "kranjcar-hajduk-2004-05",
    name: "Niko Kranjčar",
    club: "HNK Hajduk",
    season: "2004/05",
    position: "MID",
    role: "AM",
    ovr: 87,
    attack: 87,
    midfield: 90,
    defence: 53,
    goalkeeper: 6,
    scoringWeight: 1.0,
    accent: "#E32636",
    eligibleRoles: ["AM", "CM", "LW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "badelj-dinamo-2011-12",
    name: "Milan Badelj",
    club: "GNK Dinamo",
    season: "2011/12",
    position: "MID",
    role: "CM",
    ovr: 85,
    attack: 77,
    midfield: 89,
    defence: 76,
    goalkeeper: 7,
    scoringWeight: 0.7,
    accent: "#0057B8",
    eligibleRoles: ["CM", "DM", "AM"],
    ratingKind: "editorial-demo",
  },
  {
    id: "sammir-dinamo-2010-11",
    name: "Sammir",
    club: "GNK Dinamo",
    season: "2010/11",
    position: "MID",
    role: "AM",
    ovr: 88,
    attack: 89,
    midfield: 91,
    defence: 48,
    goalkeeper: 6,
    scoringWeight: 1.2,
    accent: "#0057B8",
    eligibleRoles: ["AM", "CM", "LW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "vlasic-hajduk-2016-17",
    name: "Nikola Vlašić",
    club: "HNK Hajduk",
    season: "2016/17",
    position: "MID",
    role: "AM",
    ovr: 85,
    attack: 86,
    midfield: 87,
    defence: 57,
    goalkeeper: 6,
    scoringWeight: 0.95,
    accent: "#E32636",
    eligibleRoles: ["AM", "CM", "RW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "ademi-dinamo-2019-20",
    name: "Arijan Ademi",
    club: "GNK Dinamo",
    season: "2019/20",
    position: "MID",
    role: "DM",
    ovr: 85,
    attack: 71,
    midfield: 85,
    defence: 88,
    goalkeeper: 7,
    scoringWeight: 0.55,
    accent: "#0057B8",
    eligibleRoles: ["DM", "CM"],
    ratingKind: "editorial-demo",
  },
  {
    id: "majer-dinamo-2020-21",
    name: "Lovro Majer",
    club: "GNK Dinamo",
    season: "2020/21",
    position: "MID",
    role: "AM",
    ovr: 86,
    attack: 85,
    midfield: 90,
    defence: 58,
    goalkeeper: 6,
    scoringWeight: 0.9,
    accent: "#0057B8",
    eligibleRoles: ["AM", "CM", "RW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "fruk-rijeka-2023-24",
    name: "Toni Fruk",
    club: "HNK Rijeka",
    season: "2023/24",
    position: "MID",
    role: "AM",
    ovr: 82,
    attack: 82,
    midfield: 85,
    defence: 56,
    goalkeeper: 6,
    scoringWeight: 0.82,
    accent: "#6CBFEF",
    eligibleRoles: ["AM", "CM", "RW"],
    ratingKind: "editorial-demo",
  },

  // Forwards
  {
    id: "pjaca-dinamo-2015-16",
    name: "Marko Pjaca",
    club: "GNK Dinamo",
    season: "2015/16",
    position: "FWD",
    role: "RW",
    ovr: 85,
    attack: 89,
    midfield: 80,
    defence: 42,
    goalkeeper: 6,
    scoringWeight: 1.1,
    accent: "#0057B8",
    eligibleRoles: ["RW", "LW", "ST"],
    ratingKind: "editorial-demo",
  },
  {
    id: "mandzukic-dinamo-2008-09",
    name: "Mario Mandžukić",
    club: "GNK Dinamo",
    season: "2008/09",
    position: "FWD",
    role: "ST",
    ovr: 88,
    attack: 94,
    midfield: 76,
    defence: 62,
    goalkeeper: 6,
    scoringWeight: 3.4,
    accent: "#0057B8",
    eligibleRoles: ["ST"],
    ratingKind: "editorial-demo",
  },
  {
    id: "orsic-dinamo-2020-21",
    name: "Mislav Oršić",
    club: "GNK Dinamo",
    season: "2020/21",
    position: "FWD",
    role: "LW",
    ovr: 87,
    attack: 93,
    midfield: 83,
    defence: 43,
    goalkeeper: 6,
    scoringWeight: 1.6,
    accent: "#0057B8",
    eligibleRoles: ["LW", "RW", "ST"],
    ratingKind: "editorial-demo",
  },
  {
    id: "eduardo-dinamo-2006-07",
    name: "Eduardo da Silva",
    club: "GNK Dinamo",
    season: "2006/07",
    position: "FWD",
    role: "ST",
    ovr: 90,
    attack: 96,
    midfield: 80,
    defence: 38,
    goalkeeper: 6,
    scoringWeight: 3.5,
    accent: "#0057B8",
    eligibleRoles: ["ST", "LW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "livaja-hajduk-2021-22",
    name: "Marko Livaja",
    club: "HNK Hajduk",
    season: "2021/22",
    position: "FWD",
    role: "ST",
    ovr: 89,
    attack: 94,
    midfield: 87,
    defence: 42,
    goalkeeper: 6,
    scoringWeight: 3.2,
    accent: "#E32636",
    eligibleRoles: ["ST", "AM"],
    ratingKind: "editorial-demo",
  },
  {
    id: "kramaric-rijeka-2013-14",
    name: "Andrej Kramarić",
    club: "HNK Rijeka",
    season: "2013/14",
    position: "FWD",
    role: "ST",
    ovr: 88,
    attack: 94,
    midfield: 82,
    defence: 38,
    goalkeeper: 6,
    scoringWeight: 3.0,
    accent: "#6CBFEF",
    eligibleRoles: ["ST", "LW", "RW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "olic-zagreb-2001-02",
    name: "Ivica Olić",
    club: "NK Zagreb",
    season: "2001/02",
    position: "FWD",
    role: "ST",
    ovr: 87,
    attack: 92,
    midfield: 78,
    defence: 50,
    goalkeeper: 6,
    scoringWeight: 2.7,
    accent: "#D51F2B",
    eligibleRoles: ["ST", "LW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "kalinic-hajduk-2007-08",
    name: "Nikola Kalinić",
    club: "HNK Hajduk",
    season: "2007/08",
    position: "FWD",
    role: "ST",
    ovr: 85,
    attack: 91,
    midfield: 75,
    defence: 40,
    goalkeeper: 6,
    scoringWeight: 2.5,
    accent: "#E32636",
    eligibleRoles: ["ST"],
    ratingKind: "editorial-demo",
  },
  {
    id: "soudani-dinamo-2016-17",
    name: "El Arbi Hillel Soudani",
    club: "GNK Dinamo",
    season: "2016/17",
    position: "FWD",
    role: "RW",
    ovr: 86,
    attack: 91,
    midfield: 81,
    defence: 45,
    goalkeeper: 6,
    scoringWeight: 1.8,
    accent: "#0057B8",
    eligibleRoles: ["RW", "ST", "LW"],
    ratingKind: "editorial-demo",
  },
  {
    id: "benko-rijeka-2012-13",
    name: "Leon Benko",
    club: "HNK Rijeka",
    season: "2012/13",
    position: "FWD",
    role: "ST",
    ovr: 83,
    attack: 90,
    midfield: 73,
    defence: 42,
    goalkeeper: 6,
    scoringWeight: 2.4,
    accent: "#6CBFEF",
    eligibleRoles: ["ST"],
    ratingKind: "editorial-demo",
  },
] as const;

/**
 * Exact 4-3-3 slot order:
 * GK, RB, RCB, LCB, LB, DM, CM, AM, RW, ST, LW.
 */
export const defaultDraftIds = [
  "livakovic-dinamo-2020-21",
  "srna-hajduk-2002-03",
  "simunic-dinamo-2012-13",
  "gvardiol-dinamo-2020-21",
  "pranjic-osijek-2003-04",
  "brozovic-dinamo-2013-14",
  "modric-dinamo-2007-08",
  "olmo-dinamo-2018-19",
  "pjaca-dinamo-2015-16",
  "mandzukic-dinamo-2008-09",
  "orsic-dinamo-2020-21",
] as const;

export const defaultDraftBySlot = {
  gk: defaultDraftIds[0],
  rb: defaultDraftIds[1],
  rcb: defaultDraftIds[2],
  lcb: defaultDraftIds[3],
  lb: defaultDraftIds[4],
  dm: defaultDraftIds[5],
  cm: defaultDraftIds[6],
  am: defaultDraftIds[7],
  rw: defaultDraftIds[8],
  st: defaultDraftIds[9],
  lw: defaultDraftIds[10],
} as const;

export const defaultDemo = {
  formationId: "4-3-3" as const,
  draftIds: defaultDraftIds,
  draftBySlot: defaultDraftBySlot,
  officialSeasonSeed: 38020261743,
  challengeSeed: 474,
  components: {
    attack: 92,
    midfield: 90,
    defence: 88.5,
    goalkeeper: 88,
    bench: 75,
    positionFit: 0.985,
  },
  disclosure: editorialDisclosure,
} as const;
